url: "https://moritz.lumme.de"
baseurl: ""
title: "Moritz Lumme"
author: "Moritz Lumme"
exclude:
  - README.md
  - LICENSE.md
  - flake.nix
  - flake.lock
  - gemset.nix
  - result

plugins:
  - jekyll-sitemap